# Q1  Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

In [9]:
import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])
arr=np.nan_to_num(arr,nan=0)
print(arr)

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]


In [6]:
print(arr.shape)

(2, 4)


In [12]:
print(arr[1,3])

94.0


# Q2 Move axes of 3D array to new positions

In [14]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Original Array:")
print(arr)
print("Shape:", arr.shape)

Original Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [15]:
new_arr=np.moveaxis(arr,0,2)
print(new_arr)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [16]:
print(new_arr.shape)

(2, 2, 2)


# Q3 Replace NaN values with average of columns 

In [17]:
import numpy as np
arr = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print(arr)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]
