# Q1  Combining a one and a two-dimensional NumPy Array

In [16]:
# 1-d array
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array(([34,56,78],[23,45,67]))
arr1.ndim
print(arr1)
arr2.ndim
print(arr2)

[1 2 3 4 5 6]
[[34 56 78]
 [23 45 67]]


In [18]:
# concate the numpy array in the 
arr_1=arr1.reshape(2,3)
arr3 = np.concatenate((arr_1, arr2),axis=0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [34 56 78]
 [23 45 67]]


In [19]:
# concatenate the array horizontally
arr4=np.concatenate((arr_1,arr2), axis=1)
print(arr4)

[[ 1  2  3 34 56 78]
 [ 4  5  6 23 45 67]]


# Q2 Flatten a 2d numpy array into 1d array 

In [21]:
# conver the 1-d array to @-d array
demo1=np.array([2,4,6,8])
demo2=demo1.reshape(2,2)
print(demo2)

[[2 4]
 [6 8]]


In [25]:
# use the function automatic
demo3=demo1.reshape(-1,1)
print(demo3)
print("---------------")
print(demo3.shape)

[[2]
 [4]
 [6]
 [8]]
---------------
(4, 1)


In [30]:
# use the   newaxis function to conevrt nu py array
demo4=demo1[np.newaxis,:]
print(demo1)
print(demo1.shape)
print("----------------")
print(demo4)
print(demo4.shape)

[2 4 6 8]
(4,)
----------------
[[2 4 6 8]]
(1, 4)


# Q3  Reverse a numpy array

In [35]:
#using the flip function the array reverse
exp1=np.array([23,34,45,56])
rev=np.flip(exp1)
print(rev)

[56 45 34 23]


In [39]:
# reverse the array
exp1=np.array([23,34,45,56])
rev1=exp1[::-1]
print(rev)

[56 45 34 23]


In [40]:
# reverse the numpy 2-d arrray
exp2=np.array([[1,2,3,4],[6,7,8,9]])
print(exp2)

[[1 2 3 4]
 [6 7 8 9]]


In [43]:
# us the fliud() function to flip the array
exp3=np.flipud(exp2)
exp4=np.fliplr(exp2)
exp5=np.rot90(exp2)
print(exp3)
print("---------------")
print(exp4)
print("---------------")
print(exp5)

[[6 7 8 9]
 [1 2 3 4]]
---------------
[[4 3 2 1]
 [9 8 7 6]]
---------------
[[4 9]
 [3 8]
 [2 7]
 [1 6]]


In [45]:
exp5.shape

(4, 2)

In [46]:
# rever the 3-d array
cemo=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(cemo)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [52]:
# flip the 3-d array function
cemo2=np.fliplr(cemo)
print(cemo2)
print("---------------------")
cemo3=np.rot90(cemo)
print(cemo3)

[[[7 8 9]
  [4 5 6]
  [1 2 3]]]
---------------------
[[[7 8 9]]

 [[4 5 6]]

 [[1 2 3]]]


# Q4 Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy

In [53]:
 # get maximum from the on 1-d array
femo=np.array([23,45,76,100,3,120])
print(femo.max())

120


In [57]:
# using loop
max=femo[0]
for i in femo:
    if(i>femo[0]):
        max=i
print(max)

120


In [60]:
# find the maximum in the 2-d array
femo3=np.array([[20,10,60],[10,50,80]])
print(femo3.max())

80


In [61]:
#using loop nditer numlti dim looping array
maxi=femo3[0][0]
for i in np.nditer(femo3):
    if(i>maxi):
        maxi=i;
print(maxi)

80


In [62]:
# find the mingi num
femo4=np.array([[20,10,60],[10,50,80]])
print(femo3.min())

10


In [63]:
min=femo3[0][0]
for i in np.nditer(femo3):
    if(i<min):
        min=i;
print(min)

10


In [74]:
# find the minimum in the 3-d array
femo5=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(femo5.min())
print(femo5.max())
print(femo5.std().round(2))
print(femo5.sum().round(2))
print(femo5.mean().round(2))

1
9
2.58
45
5.0


In [75]:
femo4=np.array([[20,10,60],[10,50,80]])
print(femo4.shape)

(2, 3)


In [76]:
femo6=np.rot90(femo4)
print(femo6.shape)

(3, 2)


In [77]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total = 0
for row in arr:
    for x in row:
        total += x
print(total)

21


In [78]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)

[5 7 9]


In [79]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print(arr1 - arr2)


[ 9 18 27]


In [80]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 * arr2)

[ 4 10 18]


In [82]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])

print(arr1 / arr2)
print(np.cross(arr1,arr2))

[5. 5. 6.]
[-20  10   0]


# Q5 Iterate 3D array using for loop and nditer

In [83]:
string_array=np.array([[["jai","shree","ram"],["jai","shree","jagannath"],["jai","shree","shyam"]]])
print(string_array)

[[['jai' 'shree' 'ram']
  ['jai' 'shree' 'jagannath']
  ['jai' 'shree' 'shyam']]]


In [86]:
# iterate the 3d array
for i in np.nditer(string_array):
    print(i,"\n")

jai 

shree 

ram 

jai 

shree 

jagannath 

jai 

shree 

shyam 



# Q6 Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays

In [89]:
import numpy as np
arr1 = np.array([3, 4])
arr2 = np.array([1, 0])
avg=(arr1+arr2)/2
print("Average of numpy arrays:\n",avg)

Average of numpy arrays:
 [2. 2.]


In [91]:
import numpy as np
gemo1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
gemo2= np.array([
    [7, 8, 9],
    [10, 11, 12]
])

In [98]:
# for array gemo1 first all values;
print("mean of arr1",gemo1.mean())
print("median of gemo1",np.median(gemo1))
print("mod of numpy array",np.mod(gemo1,3))

mean of arr1 3.5
median of gemo1 3.5
mod of numpy array [[1 2 0]
 [1 2 0]]


In [99]:
# for array gemo2 2d array
print("mean of arr1",gemo2.mean())
print("median of gemo1",np.median(gemo2))
print("mod of numpy array",np.mod(gemo2,3))

mean of arr1 9.5
median of gemo1 9.5
mod of numpy array [[1 2 0]
 [1 2 0]]


In [ ]:
import pandas as pd
df1=pd.DataFrame(gemo1)
print