## 1) Create numpy array and perform following operation > Convert 1D array to 2D > Print Array Attributes(Like shape, dimenssion, data type, itemsize) > Create a 3×3 NumPy array of all 9 > Create a 1D array of 10 evenly spaced values between 25 and 125 > Convert a Python list into a NumPy array > Reverse a 1D NumPy array > Create a 4×4×3 array and extract value at its second set, first row and last column > Create a 4×4 and Extract Odd Rows and Even Columns > Slice the first two rows and first two columns of econd set from a 4×4×3 array > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] > Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element. > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]

In [1]:
import numpy as np 
import pandas as pd

In [4]:
# cinvert 1D array to 2D array
arr1=np.array([10,20,30,40,50,60])
res1=arr1.reshape(2,3)
print(arr1)
print("------------")
print(res1)

[10 20 30 40 50 60]
------------
[[10 20 30]
 [40 50 60]]


In [15]:
# print the all rray atrributs of the given array
print("All atribute od arr1")
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)
print(arr1.T)
print(arr1.data)
print(arr1.flags)
print(arr1.base)
print("----------------------------")
print("all for the result array")
print(res1.ndim)
print(res1.shape)
print(res1.dtype)
print(res1.T)
print(res1.data)
print(res1.flags)
print(res1.base)

All atribute od arr1
1
(6,)
int64
[10 20 30 40 50 60]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

None
----------------------------
all for the result array
2
(2, 3)
int64
[[10 40]
 [20 50]
 [30 60]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[10 20 30 40 50 60]


In [16]:
#Create a 3×3 NumPy array of all 9
res2=np.full((3,3),9)
print(res2)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [17]:
#Create a 1D array of 10 evenly spaced values between 25 and 125
res3=np.arange(25,125,10)
print(res3)

[ 25  35  45  55  65  75  85  95 105 115]


In [29]:
# Convert a Python list into a NumPy array
list1=[1,2,3,4,5,6]
res4=np.array(list1)
print(res4)
print(res4.ndim)
print(res4.shape)
print(res4.data)

[1 2 3 4 5 6]
1
(6,)


In [30]:
#Reverse a 1D NumPy array 
arr2=np.array([23,34,45,55,67,78])
print(np.flip(arr2))

[78 67 55 45 34 23]


In [32]:
#Create a 4×4×3 array and extract value at its second set, first row and last column
res5=np.arange(48).reshape(4,4,3)
print(res5)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]


In [35]:
#Create a 4×4 and Extract Odd Rows and Even Columns
res6=np.arange(16).reshape(4,4)
print(res6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [36]:
print(res6[1::2,::2])

[[ 4  6]
 [12 14]]


In [37]:
#Slice the first two rows and first two columns of econd set from a 4×4×3 array
res5=np.arange(48).reshape(4,4,3)
print(res5[:,:2,:2])

[[[ 0  1]
  [ 3  4]]

 [[12 13]
  [15 16]]

 [[24 25]
  [27 28]]

 [[36 37]
  [39 40]]]


In [38]:
# Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]]
arr4=np.array([[23, 56, 78, 93], [71, 82,13, 24]])
print(arr4)

[[23 56 78 93]
 [71 82 13 24]]


In [40]:
for i in range(arr4.shape[0]):
    for j in range(arr4.shape[1]):
        if arr4[i][j] % 2 != 0:
            arr4[i][j] = -1
print(arr4)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [47]:
# Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] 
arr6=np.array([1, 0, 2, 0, 3, 0, 4])
print(arr6)
print(np.nonzero(arr6))

[1 0 2 0 3 0 4]
(array([0, 2, 4, 6]),)


In [50]:
for idx in np.ndindex(arr6.shape):
    if arr6[idx]!=0:
        print(idx)

(0,)
(2,)
(4,)
(6,)


In [54]:
# Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element.
demo1=np.array([1,2,3,4,5])
demo2=np.array([6,7,8,9,6])
print(demo1+demo2)
print("------------------")
print(demo1-demo2)
print("-----------------")
print(demo1*demo2)
print("-------------------")
print(demo2/demo1)

[ 7  9 11 13 11]
------------------
[-5 -5 -5 -5 -1]
-----------------
[ 6 14 24 36 30]
-------------------
[6.         3.5        2.66666667 2.25       1.2       ]


In [56]:
# Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]
demo3=np.array([15, 20, 25])
demo4=np.array([10,40,37])
result=np.dot(demo3,demo4)
print(result)

1875
